# Generated by Django 2.1.4 on 2018-12-04 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=140, verbose_name='Приложение')),
            ],
            options={
                'verbose_name': 'Приложение',
                'verbose_name_plural': 'Приложения',
            },
        ),
        migrations.AlterModelOptions(
            name='demand',
            options={'ordering': ['id'], 'verbose_name': 'Требование', 'verbose_name_plural': 'Требования'},
        ),
        migrations.AddField(
            model_name='demand',
            name='for_apps',
            field=models.ManyToManyField(to='demand.App', verbose_name='Приложения'),
        ),
    ]
