# Generated by Django 2.1.4 on 2018-12-20 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demand',
            name='title',
            field=models.CharField(db_index=True, max_length=250, verbose_name='Наименование'),
        ),
    ]
