# Generated by Django 2.1.4 on 2018-12-22 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0002_auto_20181220_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='demand',
            name='priority',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Нужно вчера'), (2, 'Надо сделать'), (3, 'Хотелки')], default=3, verbose_name='Приоритет'),
        ),
    ]
