# Generated by Django 2.1.4 on 2018-12-23 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0003_demand_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='demand',
            name='is_delited',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Удалено'),
        ),
    ]
